[default]
optimizer = true
optimizer_runs = 200
remappings = ["ds-test/=lib/ds-test/src/"]


fs_permissions = [{ access = "write", path = "./reports" }]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"

[etherscan]
ethereum={key="${ETHERSCAN_API_KEY_MAINNET}", chain=1 }
